import type { LegalStudyLearningSnapshot } from './types';

export const LEGAL_STUDY_SEED_USER_ID = 'seed-user-legal-study';
export const LEGAL_STUDY_SEED_TODAY = '2026-07-07';

export function createLegalStudySeedSnapshot(
  userId = LEGAL_STUDY_SEED_USER_ID,
  now = `${LEGAL_STUDY_SEED_TODAY}T08:00:00.000Z`
): LegalStudyLearningSnapshot {
  return {
    userId,
    capturedAt: now,
    examDate: '2026-12-20',
    availableMinutesToday: 180,
    subjects: [
      {
        id: 'subject-civil',
        userId,
        code: 'civil_law',
        name: '民法',
        priority: 1,
        createdAt: now,
      },
      {
        id: 'subject-criminal',
        userId,
        code: 'criminal_law',
        name: '刑法',
        priority: 2,
        createdAt: now,
      },
    ],
    courses: [
      {
        id: 'course-civil-basic',
        userId,
        subjectId: 'subject-civil',
        title: '民法基础精讲',
        deadline: '2026-09-30',
        source: 'bilibili',
        createdAt: now,
      },
      {
        id: 'course-criminal-basic',
        userId,
        subjectId: 'subject-criminal',
        title: '刑法总则精讲',
        deadline: '2026-08-31',
        source: 'manual',
        createdAt: now,
      },
    ],
    episodes: [
      {
        id: 'episode-civil-contract-formation',
        userId,
        courseId: 'course-civil-basic',
        title: '合同的成立',
        order: 1,
        durationMinutes: 45,
        status: 'pending',
        createdAt: now,
      },
      {
        id: 'episode-civil-contract-validity',
        userId,
        courseId: 'course-civil-basic',
        title: '合同的效力',
        order: 2,
        durationMinutes: 50,
        status: 'pending',
        createdAt: now,
      },
      {
        id: 'episode-criminal-act',
        userId,
        courseId: 'course-criminal-basic',
        title: '犯罪构成',
        order: 1,
        durationMinutes: 60,
        status: 'pending',
        lockedByUser: true,
        createdAt: now,
      },
    ],
    textbooks: [
      {
        id: 'textbook-civil',
        userId,
        subjectId: 'subject-civil',
        title: '民法考试分析',
        fileRef: 'artifact://seed/textbook-civil.pdf',
        ocrStatus: 'succeeded',
        createdAt: now,
      },
      {
        id: 'textbook-criminal',
        userId,
        subjectId: 'subject-criminal',
        title: '刑法考试分析',
        fileRef: 'artifact://seed/textbook-criminal.pdf',
        ocrStatus: 'succeeded',
        createdAt: now,
      },
    ],
    chapters: [
      {
        id: 'chapter-civil-contract-formation',
        userId,
        textbookId: 'textbook-civil',
        title: '合同成立',
        order: 1,
        pageStart: 101,
        pageEnd: 108,
        createdAt: now,
      },
      {
        id: 'chapter-civil-contract-validity',
        userId,
        textbookId: 'textbook-civil',
        title: '合同效力',
        order: 2,
        pageStart: 109,
        pageEnd: 121,
        createdAt: now,
      },
      {
        id: 'chapter-criminal-act',
        userId,
        textbookId: 'textbook-criminal',
        title: '犯罪构成',
        order: 1,
        pageStart: 31,
        pageEnd: 48,
        createdAt: now,
      },
    ],
    contentSlices: [],
    mappings: [
      {
        id: 'mapping-civil-contract-formation',
        userId,
        episodeId: 'episode-civil-contract-formation',
        chapterId: 'chapter-civil-contract-formation',
        confidence: 0.92,
        reason: '标题关键词“合同”“成立”完全匹配。',
        source: 'user_confirmed',
        createdAt: now,
      },
      {
        id: 'mapping-criminal-act',
        userId,
        episodeId: 'episode-criminal-act',
        chapterId: 'chapter-criminal-act',
        confidence: 0.88,
        reason: '课程标题与章节标题一致。',
        source: 'user_confirmed',
        createdAt: now,
      },
    ],
    cards: [
      {
        id: 'card-civil-offer-acceptance',
        userId,
        subjectId: 'subject-civil',
        textbookId: 'textbook-civil',
        chapterId: 'chapter-civil-contract-formation',
        sliceId: 'slice-civil-contract-formation-1',
        front: '合同成立通常需要哪两个意思表示阶段？',
        back: '通常需要要约与承诺两个阶段。',
        cardType: 'qa',
        status: 'confirmed',
        unlockStatus: 'locked',
        sourceEvidence: {
          pageStart: 102,
          pageEnd: 103,
          textHash: 'hash-civil-contract-formation-1',
          excerptRef: 'artifact://seed/slices/civil-contract-formation-1',
        },
        createdAt: now,
      },
      {
        id: 'card-civil-acceptance-effective',
        userId,
        subjectId: 'subject-civil',
        textbookId: 'textbook-civil',
        chapterId: 'chapter-civil-contract-formation',
        sliceId: 'slice-civil-contract-formation-2',
        front: '承诺生效时合同通常发生什么法律效果？',
        back: '承诺生效时合同成立，但还需要另行判断合同效力。',
        cardType: 'rule_understanding',
        status: 'confirmed',
        unlockStatus: 'locked',
        sourceEvidence: {
          pageStart: 104,
          pageEnd: 105,
          textHash: 'hash-civil-contract-formation-2',
          excerptRef: 'artifact://seed/slices/civil-contract-formation-2',
        },
        createdAt: now,
      },
      {
        id: 'card-civil-validity-pending',
        userId,
        subjectId: 'subject-civil',
        textbookId: 'textbook-civil',
        chapterId: 'chapter-civil-contract-validity',
        sliceId: 'slice-civil-contract-validity-1',
        front: '合同效力判断的基本层次是什么？',
        back: '先判断合同是否成立，再判断是否有效、可撤销、效力待定或无效。',
        cardType: 'concept',
        status: 'confirmed',
        unlockStatus: 'locked',
        sourceEvidence: {
          pageStart: 110,
          pageEnd: 112,
          textHash: 'hash-civil-contract-validity-1',
          excerptRef: 'artifact://seed/slices/civil-contract-validity-1',
        },
        createdAt: now,
      },
      {
        id: 'card-criminal-act-due',
        userId,
        subjectId: 'subject-criminal',
        textbookId: 'textbook-criminal',
        chapterId: 'chapter-criminal-act',
        sliceId: 'slice-criminal-act-1',
        front: '犯罪构成四要件通常包括什么？',
        back: '犯罪客体、客观方面、主体、主观方面。',
        cardType: 'qa',
        status: 'confirmed',
        unlockStatus: 'learned',
        sourceEvidence: {
          pageStart: 33,
          pageEnd: 35,
          textHash: 'hash-criminal-act-1',
          excerptRef: 'artifact://seed/slices/criminal-act-1',
        },
        createdAt: now,
      },
    ],
    reviewStates: [
      {
        id: 'review-card-criminal-act-due',
        userId,
        cardId: 'card-criminal-act-due',
        dueAt: '2026-07-07T00:00:00.000Z',
        stability: 3,
        difficulty: 6,
        elapsedDays: 2,
        scheduledDays: 2,
        reps: 3,
        lapses: 0,
        createdAt: now,
      },
    ],
    plans: [
      {
        id: 'plan-seed-today',
        userId,
        date: LEGAL_STUDY_SEED_TODAY,
        availableMinutes: 180,
        tasks: [
          {
            id: 'task-locked-criminal-act',
            kind: 'course_episode',
            subjectId: 'subject-criminal',
            refId: 'episode-criminal-act',
            estimatedMinutes: 60,
            lockedByUser: true,
          },
          {
            id: 'task-civil-contract-formation',
            kind: 'course_episode',
            subjectId: 'subject-civil',
            refId: 'episode-civil-contract-formation',
            estimatedMinutes: 45,
          },
        ],
        createdAt: now,
      },
    ],
    rejectedProposalFingerprints: [],
  };
}
